# Generated by Django 3.0.2 on 2020-04-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('carne', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('poblacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('nombre', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('representante', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500, unique=True)),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('nombre', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('a_creacion', models.IntegerField()),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('capacidad', models.IntegerField()),
                ('aconstruccion', models.IntegerField()),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonaNatural',
            fields=[
                ('cedula', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500, unique=True)),
                ('telefono', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_patrocinador', models.CharField(choices=[('Empresa', 'Empresa'), ('Persona Natural', 'Persona Natural'), ('Equipo', 'Equipo')], max_length=20)),
                ('empresa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Empresa')),
                ('equipo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipo_patrocinador', to='torneoapp.Equipo')),
                ('personanatural', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneoapp.PersonaNatural')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('fecha_hora', models.DateTimeField(primary_key=True, serialize=False, unique=True)),
                ('pts_local', models.IntegerField()),
                ('pts_visit', models.IntegerField()),
                ('arbitro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Arbitro')),
                ('eq_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_local', to='torneoapp.Equipo')),
                ('eq_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eq_visit', to='torneoapp.Equipo')),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Estadio')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorxPartido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ingreso', models.IntegerField()),
                ('min_salida', models.IntegerField()),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Jugador')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Partido')),
            ],
        ),
        migrations.CreateModel(
            name='JugadorxEquipo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateField(null=True)),
                ('fechaFin', models.DateField(null=True)),
                ('equipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo', models.IntegerField()),
                ('tipo_evento', models.CharField(choices=[('Gol', 'Gol'), ('Falta', 'Falta'), ('Tiro con barrera', 'Tiro con barrera'), ('Tiro de esquina', 'Tiro de esquina'), ('Penal', 'Penal'), ('Saque de arco', 'Saque de arco'), ('Asistencia', 'Asistencia')], max_length=30)),
                ('descripcion', models.CharField(max_length=500, null=True)),
                ('ejecutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Jugador')),
                ('jugadorxpartido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneoapp.JugadorxPartido')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneoapp.Partido')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='patrocinador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epatrocinador', to='torneoapp.Patrocinador'),
        ),
    ]
